sbt 'run data/cmap/MolePro.CMAP.sqlite exec ../schema/MoleProSchema.sql'
sbt 'run data/cmap/MolePro.CMAP.sqlite exec ../schema/MoleProPreLoadIndexes.sql'
sbt 'run data/cmap/MolePro.CMAP.sqlite load-transformers'
sbt 'run data/cmap/MolePro.CMAP.sqlite load-prefixes'
sbt -mem 4096 'run data/cmap/MolePro.CMAP.sqlite load-structures "Pubchem compound-list producer" data/cmap/CMAP-CID.tsv'
sbt -mem 4096 'run data/cmap/MolePro.CMAP.sqlite load-compounds'
sbt -mem 4096 'run data/cmap/MolePro.CMAP.sqlite load-elements "SRI node normalizer producer" data/cmap/CMAP-NCBIGeneId.tsv entrez'
sbt -mem 4096 'run data/cmap/MolePro.CMAP.sqlite add-connections pubchem data/cmap/CMAP-CID.tsv "CMAP compound-to-compound expander(score threshold = 99, maximum number = 500)" pubchem'
sbt -mem 4096 'run data/cmap/MolePro.CMAP.sqlite add-connections pubchem data/cmap/CMAP-CID.tsv "CMAP compound-to-gene transformer(score threshold = 99, maximum number = 500)" entrez'
sbt -mem 4096 'run data/cmap/MolePro.CMAP.sqlite add-connections entrez data/cmap/CMAP-NCBIGeneId.tsv "CMAP gene-to-gene expander(score threshold = 99, maximum number = 500)" entrez'
