python -u script/extract_ids.py script/components/rephub.sql
sbt 'run data/rephub/MolePro.RepHub.sqlite exec ../schema/MoleProSchema.sql'
sbt 'run data/rephub/MolePro.RepHub.sqlite exec ../schema/MoleProPreLoadIndexes.sql'
sbt 'run data/rephub/MolePro.RepHub.sqlite load-transformers'
sbt 'run data/rephub/MolePro.RepHub.sqlite load-prefixes'
sbt 'run data/rephub/MolePro.RepHub.sqlite load-structures "Pubchem compound-list producer" data/rephub/RepHub-inchikey.tsv'
sbt 'run data/rephub/MolePro.RepHub.sqlite load-structures "ChEMBL compound-list producer" data/rephub/RepHub-inchikey.tsv'
sbt 'run data/rephub/MolePro.RepHub.sqlite load-structures "ChEBI compound-list producer" data/rephub/RepHub-inchikey.tsv'
sbt 'run data/rephub/MolePro.RepHub.sqlite load-structures "GtoPdb compound-list producer" data/rephub/RepHub-inchikey.tsv'
sbt 'run data/rephub/MolePro.RepHub.sqlite load-structures "Repurposing Hub compound-list producer" data/rephub/RepHub-inchikey.tsv'
sbt 'run data/rephub/MolePro.RepHub.sqlite load-compounds'
sbt 'run data/rephub/MolePro.RepHub.sqlite load-elements "SRI node normalizer producer" data/rephub/RepHub-disease-id.tsv id'
sbt -mem 4096 'run data/rephub/MolePro.RepHub.sqlite  load-connections inchikey data/rephub/RepHub-inchikey.tsv "Repurposing Hub target transformer" hgnc'
sbt -mem 4096 'run data/rephub/MolePro.RepHub.sqlite  load-connections inchikey data/rephub/RepHub-inchikey.tsv "Repurposing Hub indication transformer" id'
sbt 'run data/rephub/MolePro.RepHub.sqlite exec ../schema/MoleProPostLoadIndexes.sql'
