python -u script/extract_ids.py script/components/rxnorm.sql 
sbt 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite exec ../schema/MoleProSchema.sql'
sbt 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite exec ../schema/MoleProPreLoadIndexes.sql'
sbt 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite load-transformers'
sbt 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite load-prefixes'
sbt 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite load-structures "Pubchem compound-list producer" data/moleprodb/rxnorm/RxNorm-CID.tsv'
sbt 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite load-compounds'
sbt 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite load-elements "UNII ingredient-list producer" data/moleprodb/rxnorm/RxNorm-UNII.tsv pubchem,unii'
sbt 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite load-elements "RxNorm drug-list producer" data/moleprodb/rxnorm/RxNorm-RXCUI.tsv rxnorm'
sbt -mem 2028 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite add-connections unii data/moleprodb/rxnorm/RxNorm-UNII.tsv "RxNorm active ingredient transformer" rxnorm'
sbt -mem 2028 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite add-connections rxnorm data/moleprodb/rxnorm/RxNorm-RXCUI.tsv "RxNorm components transformer" rxnorm'
sbt 'run data/moleprodb/rxnorm/MolePro.RxNorm.sqlite exec ../schema/MoleProPostLoadIndexes.sql'
