# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AllowList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, allowlist=None):  # noqa: E501
        """AllowList - a model defined in OpenAPI

        :param allowlist: The allowlist of this AllowList.  # noqa: E501
        :type allowlist: List[str]
        """
        self.openapi_types = {
            'allowlist': List[str]
        }

        self.attribute_map = {
            'allowlist': 'allowlist'
        }

        self._allowlist = allowlist

    @classmethod
    def from_dict(cls, dikt) -> 'AllowList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllowList of this AllowList.  # noqa: E501
        :rtype: AllowList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def allowlist(self):
        """Gets the allowlist of this AllowList.

        List of operation providers (by infores ID) that may be used to complete operation. No others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the workflow runner.  # noqa: E501

        :return: The allowlist of this AllowList.
        :rtype: List[str]
        """
        return self._allowlist

    @allowlist.setter
    def allowlist(self, allowlist):
        """Sets the allowlist of this AllowList.

        List of operation providers (by infores ID) that may be used to complete operation. No others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the workflow runner.  # noqa: E501

        :param allowlist: The allowlist of this AllowList.
        :type allowlist: List[str]
        """

        self._allowlist = allowlist
