# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DenyList(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, denylist=None):  # noqa: E501
        """DenyList - a model defined in OpenAPI

        :param denylist: The denylist of this DenyList.  # noqa: E501
        :type denylist: List[str]
        """
        self.openapi_types = {
            'denylist': List[str]
        }

        self.attribute_map = {
            'denylist': 'denylist'
        }

        self._denylist = denylist

    @classmethod
    def from_dict(cls, dikt) -> 'DenyList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DenyList of this DenyList.  # noqa: E501
        :rtype: DenyList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def denylist(self):
        """Gets the denylist of this DenyList.

        List of operation providers (by infores ID) that may not be used to complete operation. All others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the worflow runner.  # noqa: E501

        :return: The denylist of this DenyList.
        :rtype: List[str]
        """
        return self._denylist

    @denylist.setter
    def denylist(self, denylist):
        """Sets the denylist of this DenyList.

        List of operation providers (by infores ID) that may not be used to complete operation. All others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the worflow runner.  # noqa: E501

        :param denylist: The denylist of this DenyList.
        :type denylist: List[str]
        """

        self._denylist = denylist
