# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.operation_filter_kgraph_std_dev_parameters import OperationFilterKgraphStdDevParameters
from openapi_server.models.runner_parameters import RunnerParameters
from openapi_server import util

from openapi_server.models.operation_filter_kgraph_std_dev_parameters import OperationFilterKgraphStdDevParameters  # noqa: E501
from openapi_server.models.runner_parameters import RunnerParameters  # noqa: E501

class OperationFilterKgraphStdDev(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, parameters=None, runner_parameters=None):  # noqa: E501
        """OperationFilterKgraphStdDev - a model defined in OpenAPI

        :param id: The id of this OperationFilterKgraphStdDev.  # noqa: E501
        :type id: str
        :param parameters: The parameters of this OperationFilterKgraphStdDev.  # noqa: E501
        :type parameters: OperationFilterKgraphStdDevParameters
        :param runner_parameters: The runner_parameters of this OperationFilterKgraphStdDev.  # noqa: E501
        :type runner_parameters: RunnerParameters
        """
        self.openapi_types = {
            'id': str,
            'parameters': OperationFilterKgraphStdDevParameters,
            'runner_parameters': RunnerParameters
        }

        self.attribute_map = {
            'id': 'id',
            'parameters': 'parameters',
            'runner_parameters': 'runner_parameters'
        }

        self._id = id
        self._parameters = parameters
        self._runner_parameters = runner_parameters

    @classmethod
    def from_dict(cls, dikt) -> 'OperationFilterKgraphStdDev':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OperationFilterKgraphStdDev of this OperationFilterKgraphStdDev.  # noqa: E501
        :rtype: OperationFilterKgraphStdDev
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this OperationFilterKgraphStdDev.


        :return: The id of this OperationFilterKgraphStdDev.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OperationFilterKgraphStdDev.


        :param id: The id of this OperationFilterKgraphStdDev.
        :type id: str
        """
        allowed_values = ["filter_kgraph_std_dev"]  # noqa: E501
        if id not in allowed_values:
            raise ValueError(
                "Invalid value for `id` ({0}), must be one of {1}"
                .format(id, allowed_values)
            )

        self._id = id

    @property
    def parameters(self):
        """Gets the parameters of this OperationFilterKgraphStdDev.


        :return: The parameters of this OperationFilterKgraphStdDev.
        :rtype: OperationFilterKgraphStdDevParameters
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this OperationFilterKgraphStdDev.


        :param parameters: The parameters of this OperationFilterKgraphStdDev.
        :type parameters: OperationFilterKgraphStdDevParameters
        """
        if parameters is None:
            raise ValueError("Invalid value for `parameters`, must not be `None`")  # noqa: E501

        self._parameters = parameters

    @property
    def runner_parameters(self):
        """Gets the runner_parameters of this OperationFilterKgraphStdDev.


        :return: The runner_parameters of this OperationFilterKgraphStdDev.
        :rtype: RunnerParameters
        """
        return self._runner_parameters

    @runner_parameters.setter
    def runner_parameters(self, runner_parameters):
        """Sets the runner_parameters of this OperationFilterKgraphStdDev.


        :param runner_parameters: The runner_parameters of this OperationFilterKgraphStdDev.
        :type runner_parameters: RunnerParameters
        """

        self._runner_parameters = runner_parameters
