# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from molepro.openapi_server.classes.base_model_ import Model
from molepro.openapi_server import util


class ErrorMsg(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, title=None, detail=None, type=None):  # noqa: E501
        """ErrorMsg - a model defined in OpenAPI

        :param status: The status of this ErrorMsg.  # noqa: E501
        :type status: int
        :param title: The title of this ErrorMsg.  # noqa: E501
        :type title: str
        :param detail: The detail of this ErrorMsg.  # noqa: E501
        :type detail: str
        :param type: The type of this ErrorMsg.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'status': int,
            'title': str,
            'detail': str,
            'type': str
        }

        self.attribute_map = {
            'status': 'status',
            'title': 'title',
            'detail': 'detail',
            'type': 'type'
        }

        self._status = status
        self._title = title
        self._detail = detail
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorMsg':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error_msg of this ErrorMsg.  # noqa: E501
        :rtype: ErrorMsg
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this ErrorMsg.


        :return: The status of this ErrorMsg.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ErrorMsg.


        :param status: The status of this ErrorMsg.
        :type status: int
        """

        self._status = status

    @property
    def title(self):
        """Gets the title of this ErrorMsg.


        :return: The title of this ErrorMsg.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ErrorMsg.


        :param title: The title of this ErrorMsg.
        :type title: str
        """

        self._title = title

    @property
    def detail(self):
        """Gets the detail of this ErrorMsg.


        :return: The detail of this ErrorMsg.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this ErrorMsg.


        :param detail: The detail of this ErrorMsg.
        :type detail: str
        """

        self._detail = detail

    @property
    def type(self):
        """Gets the type of this ErrorMsg.


        :return: The type of this ErrorMsg.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ErrorMsg.


        :param type: The type of this ErrorMsg.
        :type type: str
        """

        self._type = type
