# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.classes.base_model_ import Model
from openapi_server.classes.gene_info import GeneInfo
from openapi_server import util

from openapi_server.classes.gene_info import GeneInfo  # noqa: E501

class GeneListAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, elements=None):  # noqa: E501
        """GeneListAllOf - a model defined in OpenAPI

        :param elements: The elements of this GeneListAllOf.  # noqa: E501
        :type elements: List[GeneInfo]
        """
        self.openapi_types = {
            'elements': List[GeneInfo]
        }

        self.attribute_map = {
            'elements': 'elements'
        }

        self._elements = elements

    @classmethod
    def from_dict(cls, dikt) -> 'GeneListAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The gene_list_allOf of this GeneListAllOf.  # noqa: E501
        :rtype: GeneListAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def elements(self):
        """Gets the elements of this GeneListAllOf.

        Members of the gene list.  # noqa: E501

        :return: The elements of this GeneListAllOf.
        :rtype: List[GeneInfo]
        """
        return self._elements

    @elements.setter
    def elements(self, elements):
        """Sets the elements of this GeneListAllOf.

        Members of the gene list.  # noqa: E501

        :param elements: The elements of this GeneListAllOf.
        :type elements: List[GeneInfo]
        """

        self._elements = elements
