# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from molepro.openapi_server.classes.base_model_ import Model
from molepro.openapi_server import util


class TransformerInfoProperties(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, source_url=None, source_version=None, terms_of_service=None, method=None, method_url=None):  # noqa: E501
        """TransformerInfoProperties - a model defined in OpenAPI

        :param source_url: The source_url of this TransformerInfoProperties.  # noqa: E501
        :type source_url: str
        :param source_version: The source_version of this TransformerInfoProperties.  # noqa: E501
        :type source_version: str
        :param terms_of_service: The terms_of_service of this TransformerInfoProperties.  # noqa: E501
        :type terms_of_service: str
        :param method: The method of this TransformerInfoProperties.  # noqa: E501
        :type method: str
        :param method_url: The method_url of this TransformerInfoProperties.  # noqa: E501
        :type method_url: str
        """
        self.openapi_types = {
            'source_url': str,
            'source_version': str,
            'terms_of_service': str,
            'method': str,
            'method_url': str
        }

        self.attribute_map = {
            'source_url': 'source_url',
            'source_version': 'source_version',
            'terms_of_service': 'terms_of_service',
            'method': 'method',
            'method_url': 'method_url'
        }

        self._source_url = source_url
        self._source_version = source_version
        self._terms_of_service = terms_of_service
        self._method = method
        self._method_url = method_url

    @classmethod
    def from_dict(cls, dikt) -> 'TransformerInfoProperties':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transformer_info_properties of this TransformerInfoProperties.  # noqa: E501
        :rtype: TransformerInfoProperties
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_url(self):
        """Gets the source_url of this TransformerInfoProperties.

        URL for underlying data or a wrapped service.  # noqa: E501

        :return: The source_url of this TransformerInfoProperties.
        :rtype: str
        """
        return self._source_url

    @source_url.setter
    def source_url(self, source_url):
        """Sets the source_url of this TransformerInfoProperties.

        URL for underlying data or a wrapped service.  # noqa: E501

        :param source_url: The source_url of this TransformerInfoProperties.
        :type source_url: str
        """

        self._source_url = source_url

    @property
    def source_version(self):
        """Gets the source_version of this TransformerInfoProperties.

        Version of the underlying source or data.  # noqa: E501

        :return: The source_version of this TransformerInfoProperties.
        :rtype: str
        """
        return self._source_version

    @source_version.setter
    def source_version(self, source_version):
        """Sets the source_version of this TransformerInfoProperties.

        Version of the underlying source or data.  # noqa: E501

        :param source_version: The source_version of this TransformerInfoProperties.
        :type source_version: str
        """

        self._source_version = source_version

    @property
    def terms_of_service(self):
        """Gets the terms_of_service of this TransformerInfoProperties.

        Link to the page that describes the terms of service for the transformer.  # noqa: E501

        :return: The terms_of_service of this TransformerInfoProperties.
        :rtype: str
        """
        return self._terms_of_service

    @terms_of_service.setter
    def terms_of_service(self, terms_of_service):
        """Sets the terms_of_service of this TransformerInfoProperties.

        Link to the page that describes the terms of service for the transformer.  # noqa: E501

        :param terms_of_service: The terms_of_service of this TransformerInfoProperties.
        :type terms_of_service: str
        """

        self._terms_of_service = terms_of_service

    @property
    def method(self):
        """Gets the method of this TransformerInfoProperties.

        A method used to generate output lists.  # noqa: E501

        :return: The method of this TransformerInfoProperties.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this TransformerInfoProperties.

        A method used to generate output lists.  # noqa: E501

        :param method: The method of this TransformerInfoProperties.
        :type method: str
        """

        self._method = method

    @property
    def method_url(self):
        """Gets the method_url of this TransformerInfoProperties.

        Link to a description of a method used to generate output lists.  # noqa: E501

        :return: The method_url of this TransformerInfoProperties.
        :rtype: str
        """
        return self._method_url

    @method_url.setter
    def method_url(self, method_url):
        """Sets the method_url of this TransformerInfoProperties.

        Link to a description of a method used to generate output lists.  # noqa: E501

        :param method_url: The method_url of this TransformerInfoProperties.
        :type method_url: str
        """

        self._method_url = method_url
