# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.element import Element
from openapi_server import util

from openapi_server.models.element import Element  # noqa: E501

class CollectionAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, elements=None):  # noqa: E501
        """CollectionAllOf - a model defined in OpenAPI

        :param elements: The elements of this CollectionAllOf.  # noqa: E501
        :type elements: List[Element]
        """
        self.openapi_types = {
            'elements': List[Element]
        }

        self.attribute_map = {
            'elements': 'elements'
        }

        self._elements = elements

    @classmethod
    def from_dict(cls, dikt) -> 'CollectionAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The collection_allOf of this CollectionAllOf.  # noqa: E501
        :rtype: CollectionAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def elements(self):
        """Gets the elements of this CollectionAllOf.

        Members of the gene list.  # noqa: E501

        :return: The elements of this CollectionAllOf.
        :rtype: List[Element]
        """
        return self._elements

    @elements.setter
    def elements(self, elements):
        """Sets the elements of this CollectionAllOf.

        Members of the gene list.  # noqa: E501

        :param elements: The elements of this CollectionAllOf.
        :type elements: List[Element]
        """

        self._elements = elements
