apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appname }}
  namespace: molepro
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.logs.storageSize }}