# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.compound_info import CompoundInfo
from openapi_server.models.gene_info import GeneInfo
from openapi_server.models.model_property import ModelProperty
from openapi_server import util

from openapi_server.models.compound_info import CompoundInfo  # noqa: E501
from openapi_server.models.gene_info import GeneInfo  # noqa: E501
from openapi_server.models.model_property import ModelProperty  # noqa: E501

class TransformerQuery(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, genes=None, compounds=None, controls=None):  # noqa: E501
        """TransformerQuery - a model defined in OpenAPI

        :param genes: The genes of this TransformerQuery.  # noqa: E501
        :type genes: List[GeneInfo]
        :param compounds: The compounds of this TransformerQuery.  # noqa: E501
        :type compounds: List[CompoundInfo]
        :param controls: The controls of this TransformerQuery.  # noqa: E501
        :type controls: List[ModelProperty]
        """
        self.openapi_types = {
            'genes': List[GeneInfo],
            'compounds': List[CompoundInfo],
            'controls': List[ModelProperty]
        }

        self.attribute_map = {
            'genes': 'genes',
            'compounds': 'compounds',
            'controls': 'controls'
        }

        self._genes = genes
        self._compounds = compounds
        self._controls = controls

    @classmethod
    def from_dict(cls, dikt) -> 'TransformerQuery':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The transformer_query of this TransformerQuery.  # noqa: E501
        :rtype: TransformerQuery
        """
        return util.deserialize_model(dikt, cls)

    @property
    def genes(self):
        """Gets the genes of this TransformerQuery.

        List of genes that will be transformed. Required for expanders and filters; should be omitted for producers.  # noqa: E501

        :return: The genes of this TransformerQuery.
        :rtype: List[GeneInfo]
        """
        return self._genes

    @genes.setter
    def genes(self, genes):
        """Sets the genes of this TransformerQuery.

        List of genes that will be transformed. Required for expanders and filters; should be omitted for producers.  # noqa: E501

        :param genes: The genes of this TransformerQuery.
        :type genes: List[GeneInfo]
        """

        self._genes = genes

    @property
    def compounds(self):
        """Gets the compounds of this TransformerQuery.

        List of compounds that will be transformed. Required for expanders and filters; should be omitted for producers.  # noqa: E501

        :return: The compounds of this TransformerQuery.
        :rtype: List[CompoundInfo]
        """
        return self._compounds

    @compounds.setter
    def compounds(self, compounds):
        """Sets the compounds of this TransformerQuery.

        List of compounds that will be transformed. Required for expanders and filters; should be omitted for producers.  # noqa: E501

        :param compounds: The compounds of this TransformerQuery.
        :type compounds: List[CompoundInfo]
        """

        self._compounds = compounds

    @property
    def controls(self):
        """Gets the controls of this TransformerQuery.

        Values that control the behavior of the transformer. Names of the controls must match the names specified in the transformer's definition and values must match types (and possibly  allowed_values) specified in the transformer's definition.  # noqa: E501

        :return: The controls of this TransformerQuery.
        :rtype: List[ModelProperty]
        """
        return self._controls

    @controls.setter
    def controls(self, controls):
        """Sets the controls of this TransformerQuery.

        Values that control the behavior of the transformer. Names of the controls must match the names specified in the transformer's definition and values must match types (and possibly  allowed_values) specified in the transformer's definition.  # noqa: E501

        :param controls: The controls of this TransformerQuery.
        :type controls: List[ModelProperty]
        """
        if controls is None:
            raise ValueError("Invalid value for `controls`, must not be `None`")  # noqa: E501

        self._controls = controls
