# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.runner_parameters import RunnerParameters
from openapi_server import util

from openapi_server.models.runner_parameters import RunnerParameters  # noqa: E501

class OperationLookup(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, parameters=None, runner_parameters=None):  # noqa: E501
        """OperationLookup - a model defined in OpenAPI

        :param id: The id of this OperationLookup.  # noqa: E501
        :type id: str
        :param parameters: The parameters of this OperationLookup.  # noqa: E501
        :type parameters: object
        :param runner_parameters: The runner_parameters of this OperationLookup.  # noqa: E501
        :type runner_parameters: RunnerParameters
        """
        self.openapi_types = {
            'id': str,
            'parameters': object,
            'runner_parameters': RunnerParameters
        }

        self.attribute_map = {
            'id': 'id',
            'parameters': 'parameters',
            'runner_parameters': 'runner_parameters'
        }

        self._id = id
        self._parameters = parameters
        self._runner_parameters = runner_parameters

    @classmethod
    def from_dict(cls, dikt) -> 'OperationLookup':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OperationLookup of this OperationLookup.  # noqa: E501
        :rtype: OperationLookup
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this OperationLookup.


        :return: The id of this OperationLookup.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this OperationLookup.


        :param id: The id of this OperationLookup.
        :type id: str
        """
        allowed_values = ["lookup"]  # noqa: E501
        if id not in allowed_values:
            raise ValueError(
                "Invalid value for `id` ({0}), must be one of {1}"
                .format(id, allowed_values)
            )

        self._id = id

    @property
    def parameters(self):
        """Gets the parameters of this OperationLookup.


        :return: The parameters of this OperationLookup.
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this OperationLookup.


        :param parameters: The parameters of this OperationLookup.
        :type parameters: object
        """

        self._parameters = parameters

    @property
    def runner_parameters(self):
        """Gets the runner_parameters of this OperationLookup.


        :return: The runner_parameters of this OperationLookup.
        :rtype: RunnerParameters
        """
        return self._runner_parameters

    @runner_parameters.setter
    def runner_parameters(self, runner_parameters):
        """Sets the runner_parameters of this OperationLookup.


        :param runner_parameters: The runner_parameters of this OperationLookup.
        :type runner_parameters: RunnerParameters
        """

        self._runner_parameters = runner_parameters
