# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.operation_annotate_runner_parameters_one_of import OperationAnnotateRunnerParametersOneOf
from openapi_server.models.operation_annotate_runner_parameters_one_of1 import OperationAnnotateRunnerParametersOneOf1
from openapi_server import util

from openapi_server.models.operation_annotate_runner_parameters_one_of import OperationAnnotateRunnerParametersOneOf  # noqa: E501
from openapi_server.models.operation_annotate_runner_parameters_one_of1 import OperationAnnotateRunnerParametersOneOf1  # noqa: E501

class OperationAnnotateRunnerParameters(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, allowlist=None, denylist=None):  # noqa: E501
        """OperationAnnotateRunnerParameters - a model defined in OpenAPI

        :param allowlist: The allowlist of this OperationAnnotateRunnerParameters.  # noqa: E501
        :type allowlist: List[str]
        :param denylist: The denylist of this OperationAnnotateRunnerParameters.  # noqa: E501
        :type denylist: List[str]
        """
        self.openapi_types = {
            'allowlist': List[str],
            'denylist': List[str]
        }

        self.attribute_map = {
            'allowlist': 'allowlist',
            'denylist': 'denylist'
        }

        self._allowlist = allowlist
        self._denylist = denylist

    @classmethod
    def from_dict(cls, dikt) -> 'OperationAnnotateRunnerParameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OperationAnnotate_runner_parameters of this OperationAnnotateRunnerParameters.  # noqa: E501
        :rtype: OperationAnnotateRunnerParameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def allowlist(self):
        """Gets the allowlist of this OperationAnnotateRunnerParameters.

        List of operation providers (by infores ID) that may be used to complete operation. No others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the workflow runner.  # noqa: E501

        :return: The allowlist of this OperationAnnotateRunnerParameters.
        :rtype: List[str]
        """
        return self._allowlist

    @allowlist.setter
    def allowlist(self, allowlist):
        """Sets the allowlist of this OperationAnnotateRunnerParameters.

        List of operation providers (by infores ID) that may be used to complete operation. No others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the workflow runner.  # noqa: E501

        :param allowlist: The allowlist of this OperationAnnotateRunnerParameters.
        :type allowlist: List[str]
        """

        self._allowlist = allowlist

    @property
    def denylist(self):
        """Gets the denylist of this OperationAnnotateRunnerParameters.

        List of operation providers (by infores ID) that may not be used to complete operation. All others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the worflow runner.  # noqa: E501

        :return: The denylist of this OperationAnnotateRunnerParameters.
        :rtype: List[str]
        """
        return self._denylist

    @denylist.setter
    def denylist(self, denylist):
        """Sets the denylist of this OperationAnnotateRunnerParameters.

        List of operation providers (by infores ID) that may not be used to complete operation. All others will be used. A full list of operation providers for each operation with infores ID's is available through the '/services' endpoint of the worflow runner.  # noqa: E501

        :param denylist: The denylist of this OperationAnnotateRunnerParameters.
        :type denylist: List[str]
        """

        self._denylist = denylist
