# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Attribute(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, value=None, type=None, source=None, url=None, provided_by=None):  # noqa: E501
        """Attribute - a model defined in OpenAPI

        :param name: The name of this Attribute.  # noqa: E501
        :type name: str
        :param value: The value of this Attribute.  # noqa: E501
        :type value: str
        :param type: The type of this Attribute.  # noqa: E501
        :type type: str
        :param source: The source of this Attribute.  # noqa: E501
        :type source: str
        :param url: The url of this Attribute.  # noqa: E501
        :type url: str
        :param provided_by: The provided_by of this Attribute.  # noqa: E501
        :type provided_by: str
        """
        self.openapi_types = {
            'name': str,
            'value': str,
            'type': str,
            'source': str,
            'url': str,
            'provided_by': str
        }

        self.attribute_map = {
            'name': 'name',
            'value': 'value',
            'type': 'type',
            'source': 'source',
            'url': 'url',
            'provided_by': 'provided_by'
        }

        self._name = name
        self._value = value
        self._type = type
        self._source = source
        self._url = url
        self._provided_by = provided_by

    @classmethod
    def from_dict(cls, dikt) -> 'Attribute':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The attribute of this Attribute.  # noqa: E501
        :rtype: Attribute
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self):
        """Gets the name of this Attribute.

        Name of the attribute.  # noqa: E501

        :return: The name of this Attribute.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Attribute.

        Name of the attribute.  # noqa: E501

        :param name: The name of this Attribute.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def value(self):
        """Gets the value of this Attribute.

        Value of the attribute.  # noqa: E501

        :return: The value of this Attribute.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Attribute.

        Value of the attribute.  # noqa: E501

        :param value: The value of this Attribute.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def type(self):
        """Gets the type of this Attribute.

        CURIE of the semantic type of the attribute, from the EDAM ontology if possible.  # noqa: E501

        :return: The type of this Attribute.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Attribute.

        CURIE of the semantic type of the attribute, from the EDAM ontology if possible.  # noqa: E501

        :param type: The type of this Attribute.
        :type type: str
        """

        self._type = type

    @property
    def source(self):
        """Gets the source of this Attribute.

        Source of the attribute, as a CURIE prefix.  # noqa: E501

        :return: The source of this Attribute.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Attribute.

        Source of the attribute, as a CURIE prefix.  # noqa: E501

        :param source: The source of this Attribute.
        :type source: str
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    @property
    def url(self):
        """Gets the url of this Attribute.

        URL for additional information.  # noqa: E501

        :return: The url of this Attribute.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Attribute.

        URL for additional information.  # noqa: E501

        :param url: The url of this Attribute.
        :type url: str
        """

        self._url = url

    @property
    def provided_by(self):
        """Gets the provided_by of this Attribute.

        Transformer that produced the attribute's value.  # noqa: E501

        :return: The provided_by of this Attribute.
        :rtype: str
        """
        return self._provided_by

    @provided_by.setter
    def provided_by(self, provided_by):
        """Sets the provided_by of this Attribute.

        Transformer that produced the attribute's value.  # noqa: E501

        :param provided_by: The provided_by of this Attribute.
        :type provided_by: str
        """

        self._provided_by = provided_by
