# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.predicate import Predicate
from openapi_server import util

from openapi_server.models.predicate import Predicate  # noqa: E501

class KnowledgeMap(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, input_class=None, output_class=None, predicates=None):  # noqa: E501
        """KnowledgeMap - a model defined in OpenAPI

        :param input_class: The input_class of this KnowledgeMap.  # noqa: E501
        :type input_class: str
        :param output_class: The output_class of this KnowledgeMap.  # noqa: E501
        :type output_class: str
        :param predicates: The predicates of this KnowledgeMap.  # noqa: E501
        :type predicates: List[Predicate]
        """
        self.openapi_types = {
            'input_class': str,
            'output_class': str,
            'predicates': List[Predicate]
        }

        self.attribute_map = {
            'input_class': 'input_class',
            'output_class': 'output_class',
            'predicates': 'predicates'
        }

        self._input_class = input_class
        self._output_class = output_class
        self._predicates = predicates

    @classmethod
    def from_dict(cls, dikt) -> 'KnowledgeMap':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The knowledge_map of this KnowledgeMap.  # noqa: E501
        :rtype: KnowledgeMap
        """
        return util.deserialize_model(dikt, cls)

    @property
    def input_class(self):
        """Gets the input_class of this KnowledgeMap.

        BioLink class for the members of the input list.  # noqa: E501

        :return: The input_class of this KnowledgeMap.
        :rtype: str
        """
        return self._input_class

    @input_class.setter
    def input_class(self, input_class):
        """Sets the input_class of this KnowledgeMap.

        BioLink class for the members of the input list.  # noqa: E501

        :param input_class: The input_class of this KnowledgeMap.
        :type input_class: str
        """

        self._input_class = input_class

    @property
    def output_class(self):
        """Gets the output_class of this KnowledgeMap.

        BioLink class for the members of the output list.  # noqa: E501

        :return: The output_class of this KnowledgeMap.
        :rtype: str
        """
        return self._output_class

    @output_class.setter
    def output_class(self, output_class):
        """Sets the output_class of this KnowledgeMap.

        BioLink class for the members of the output list.  # noqa: E501

        :param output_class: The output_class of this KnowledgeMap.
        :type output_class: str
        """

        self._output_class = output_class

    @property
    def predicates(self):
        """Gets the predicates of this KnowledgeMap.

        Predicates describing relationships between subjects and objects.  # noqa: E501

        :return: The predicates of this KnowledgeMap.
        :rtype: List[Predicate]
        """
        return self._predicates

    @predicates.setter
    def predicates(self, predicates):
        """Sets the predicates of this KnowledgeMap.

        Predicates describing relationships between subjects and objects.  # noqa: E501

        :param predicates: The predicates of this KnowledgeMap.
        :type predicates: List[Predicate]
        """

        self._predicates = predicates
