CREATE TABLE METABOLITE (
    METABOLITE_ID INTEGER PRIMARY KEY,
    ACCESSION     TEXT  UNIQUE  NOT NULL,
    NAME          TEXT  UNIQUE  NOT NULL  COLLATE NOCASE
);


CREATE TABLE NAME (
    NAME_ID        INTEGER PRIMARY KEY,
    METABOLITE_ID  INT     NOT NULL,
    NAME           TEXT    NOT NULL  COLLATE NOCASE,
    NAME_TYPE      TEXT    NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    UNIQUE (METABOLITE_ID, NAME, NAME_TYPE)
);


CREATE TABLE IDENTIFIER (
    IDENTIFIER_ID  INTEGER PRIMARY KEY,
    METABOLITE_ID  INT     NOT NULL,
    TAG_ID         INT     NOT NULL,
    XREF           TEXT    NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID),
    UNIQUE (METABOLITE_ID, TAG_ID, XREF)
);


CREATE TABLE TAXONOMY (
    TAXONOMY_ID          INTEGER PRIMARY KEY,
    DESCRIPTION          TEXT    NOT NULL,
    DIRECT_PARENT        TEXT    NOT NULL,
    KINGDOM              TEXT    NOT NULL,
    SUPERCLASS           TEXT    NOT NULL,
    TAXONOMY_CLASS       TEXT    NOT NULL,
    SUBCLASS             TEXT,
    MOLECULAR_FRAMEWORK  TEXT,
    UNIQUE (DESCRIPTION, DIRECT_PARENT, KINGDOM, SUPERCLASS, TAXONOMY_CLASS, SUBCLASS, MOLECULAR_FRAMEWORK)
);


CREATE TABLE TAXONOMY_MAP (
    TAXONOMY_MAP_ID  INTEGER PRIMARY KEY,
    METABOLITE_ID    INT     NOT NULL,
    TAXONOMY_ID      INT     NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    FOREIGN KEY (TAXONOMY_ID) REFERENCES TAXONOMY(TAXONOMY_ID),
    UNIQUE (METABOLITE_ID, TAXONOMY_ID)
);


CREATE TABLE TAXONOMY_PROPERTY (
    TAXONOMY_PROPERTY_ID  INTEGER PRIMARY KEY,
    METABOLITE_ID         INT     NOT NULL,
    PROPERTY_ID           INT     NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY (PROPERTY_ID),
    UNIQUE (METABOLITE_ID, PROPERTY_ID)
);


CREATE TABLE ONTOLOGY (
    ONTOLOGY_ID         INTEGER PRIMARY KEY,
    ONTOLOGY_PARENT_ID  INT,
    ONTOLOGY_TERM       TEXT    NOT NULL,
    DEFINITION          TEXT,
    XML_PARENT_ID       INT,
    ONTOLOGY_LEVEL      INT     NOT NULL,
    ONTOLOGY_TYPE       TEXT    NOT NULL,
    FOREIGN KEY (ONTOLOGY_PARENT_ID) REFERENCES ONTOLOGY (ONTOLOGY_PARENT_ID),
    UNIQUE (ONTOLOGY_TERM, DEFINITION, ONTOLOGY_LEVEL)
);


CREATE TABLE ONTOLOGY_MAP (
    ONTOLOGY_MAP_MAP_ID  INTEGER PRIMARY KEY,
    METABOLITE_ID        INT     NOT NULL,
    ONTOLOGY_ID          INT     NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    FOREIGN KEY (ONTOLOGY_ID) REFERENCES ONTOLOGY(ONTOLOGY_ID),
    UNIQUE (METABOLITE_ID, ONTOLOGY_ID)
);


CREATE TABLE ONTOLOGY_SYNONYM (
    ONTOLOGY_SYNONYM_ID  INTEGER PRIMARY KEY,
    ONTOLOGY_ID          INT     NOT NULL,
    ONTOLOGY_SYNONYM     TEXT    NOT NULL,
    FOREIGN KEY (ONTOLOGY_ID) REFERENCES ONTOLOGY(ONTOLOGY_ID),
    UNIQUE (ONTOLOGY_ID, ONTOLOGY_SYNONYM)
);

CREATE TABLE PATHWAY (
    PATHWAY_ID    INTEGER PRIMARY KEY,
    PATHWAY_NAME  TEXT    NOT NULL,
    SMPDB_ID      TEXT,
    KEGG_MAP_ID   TEXT,
    UNIQUE (PATHWAY_NAME, SMPDB_ID, KEGG_MAP_ID)
);


CREATE TABLE PATHWAY_MAP (
    PATHWAY_MAP_ID  INTEGER PRIMARY KEY,
    METABOLITE_ID   INT     NOT NULL,
    PATHWAY_ID      INT     NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    FOREIGN KEY (PATHWAY_ID) REFERENCES PATHWAY(PATHWAY_ID),
    UNIQUE (METABOLITE_ID, PATHWAY_ID)
);


CREATE TABLE CONCENTRATION (
    CONCENTRATION_ID        INTEGER PRIMARY KEY,
    METABOLITE_ID           INT     NOT NULL,
    ABNORMAL_CONCENTRATION  INT     NOT NULL,
    BIOSPECIMEN             TEXT,
    CONCENTRATION_VALUE     TEXT,
    CONCENTRATION_UNITS     TEXT,
    AGE                     TEXT,
    GENDER                  TEXT,
    SUBJECT_CONDITION       TEXT,
    PATIENT_INFORMATION     TEXT,
    COMMENT                 TEXT,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID)
);


CREATE TABLE CONCENTRATION_REFERENCE_MAP (
    CONCENTRATION_REFERENCE_ID INTEGER PRIMARY KEY,
    CONCENTRATION_ID           INT     NOT NULL,
    REFERENCE_ID               INT     NOT NULL,
    FOREIGN KEY (CONCENTRATION_ID) REFERENCES CONCENTRATION_ID (CONCENTRATION_ID),
    FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID)
);


CREATE TABLE DISEASE (
    DISEASE_ID  INTEGER PRIMARY KEY,
    DISEASE     TEXT    UNIQUE  NOT NULL,
    OMIM_ID     INT
);


CREATE TABLE DISEASE_MAP (
    DISEASE_MAP_ID  INTEGER PRIMARY KEY,
    METABOLITE_ID   INT     NOT NULL,
    DISEASE_ID      INT     NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    FOREIGN KEY (DISEASE_ID) REFERENCES DISEASE (DISEASE_ID),
    UNIQUE (METABOLITE_ID, DISEASE_ID)
);


CREATE TABLE DISEASE_REFERENCE_MAP (
    DISEASE_REFERENCE_ID INTEGER PRIMARY KEY,
    METABOLITE_ID        INT     NOT NULL,
    DISEASE_ID           INT     NOT NULL,
    REFERENCE_ID         INT     NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    FOREIGN KEY (DISEASE_ID) REFERENCES DISEASE (DISEASE_ID),
    FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID),
    UNIQUE (METABOLITE_ID, DISEASE_ID, REFERENCE_ID)
);


CREATE TABLE REFERENCE (
    REFERENCE_ID  INTEGER PRIMARY KEY,
    REFERENCE     TEXT    UNIQUE  NOT NULL,
    PUBMED_ID     INT
);


CREATE TABLE REFERENCE_MAP (
    REFERENCE_MAP_ID  INTEGER PRIMARY KEY,
    METABOLITE_ID     INT     NOT NULL,
    REFERENCE_ID      INT     NOT NULL,
    TAG_ID            INT     NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    FOREIGN KEY (REFERENCE_ID) REFERENCES REFERENCE (REFERENCE_ID),
    FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID),
    UNIQUE (METABOLITE_ID, REFERENCE_ID, TAG_ID)
);


CREATE TABLE PROTEIN (
    PROTEIN_ID         INTEGER PRIMARY KEY,
    PROTEIN_ACCESSION  TEXT    UNIQUE  NOT NULL,
    PROTEIN_NAME       TEXT    NOT NULL,
    UNIPROT_ID         TEXT    NOT NULL,
    GENE_NAME          TEXT    NOT NULL,
    PROTEIN_TYPE       TEXT
);


CREATE TABLE PROTEIN_MAP (
    PROTEIN_MAP_ID  INTEGER PRIMARY KEY,
    METABOLITE_ID   INT     NOT NULL,
    PROTEIN_ID      INT     NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    FOREIGN KEY (PROTEIN_ID) REFERENCES PROTEIN (PROTEIN_ID),
    UNIQUE (METABOLITE_ID, PROTEIN_ID)
);


CREATE TABLE METABOLITE_PROPERTY (
    METABOLITE_PROPERTY_ID INTEGER PRIMARY KEY,
    METABOLITE_ID          INT     NOT NULL,
    PROPERTY_ID            INT     NOT NULL,
    FOREIGN KEY (METABOLITE_ID) REFERENCES METABOLITE (METABOLITE_ID),
    FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY (PROPERTY_ID),
    UNIQUE (METABOLITE_ID, PROPERTY_ID)
);


CREATE TABLE PROPERTY (
    PROPERTY_ID  INTEGER  PRIMARY KEY,
    TAG_ID       INT      NOT NULL,
    KIND         TEXT,
    VALUE        TEXT     NOT NULL,
    SOURCE       TEXT,
    FOREIGN KEY (TAG_ID) REFERENCES TAG(TAG_ID),
    UNIQUE (TAG_ID, KIND, VALUE, SOURCE)
);


CREATE TABLE TAG (
    TAG_ID INTEGER PRIMARY KEY,
    TAG    TEXT    UNIQUE  NOT NULL
);
