# This workflow will install Python dependencies, run tests and lint with a single version of Python
# This workflow was programmed to:
#   1. be triggered manually (on: workflow_dispatch:), see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
#   2. be triggered by cron scheduling (on: schedule:) to run at midnight UTC
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily ITRB CI Translator testing

# Controls when the workflow will run
on:
# Triggers the workflow on cron event but only for the CI branch
  workflow_dispatch:
  schedule:
#   - cron: '00 00 * * *'   # midnight UTC
    - cron: '20 08 * * *'   # 8:20AM UTC
jobs:
# This workflow contains a multiple jobs to test each transformer

  bigg_models:
    runs-on: ubuntu-latest
    steps:    
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-ci }          
 
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/bigg_models.feature

  bindingdb:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-ci }

        - name: download all the required python modules
          run: pip install -r test/requirements.txt

        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/bindingdb.feature 
