name: Debug 3 Make a POST Request Using github-script

# Controls when the workflow will run
on:
# Triggers the workflow on cron event but only for the CI branch
  workflow_dispatch:
#  schedule:
#   - cron: '00 00 * * *'   # midnight UTC
#    - cron: '20 08 * * *'   # 8:20AM UTC

jobs:
  post-request:
    runs-on: ubuntu-latest
    steps:
      - name: Make a POST request using github-script
        uses: actions/github-script@v6
        with:
          script: |
            const response = await fetch('https://molepro-rxnorm-transformer.ci.transltr.io/rxnorm/molecules/transform', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify(

              {
                  "controls": [
                      {
                          "name": "compound",
                          "value": "aspirin"
                      },
                      {
                          "name": "compound",
                          "value": "UNII:0258808825"
                      }
                  ]
              }
              
              
              ),
            });
            const result = await response.json();
            console.log(result);
