

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# This workflow was programmed to:
#   1. be triggered manually (on: workflow_dispatch:), see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
#   2. be triggered by cron scheduling (on: schedule:) to run at midnight UTC
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# https://github.com/broadinstitute/molecular-data-provider/blob/master/.github/workflows/main.yml
name: Daily Broad Institute Translator testing

on:
  workflow_dispatch:
  schedule:
  - cron: '40 07 * * *'   # 7:40AM UTC

jobs:
# This workflow contains a multiple jobs to test each transformer
  bigg_models:
    runs-on: ubuntu-latest
    steps:    
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }   
 
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/bigg_models.feature  

  bindingdb:
    runs-on: ubuntu-latest
    steps:    
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }   
 
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/bindingdb.feature 

  chebi:
    runs-on: ubuntu-latest
    steps:    
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/chebi.feature

  chembank:
    runs-on: ubuntu-latest
    steps:    
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/chembank.feature

  chembl:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/chembl.feature

  cmap:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }   
 
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/cmap.feature

  ctd:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }   
 
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/ctd.feature

  ctrp:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }   
 
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/ctrp.feature


  depmap:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }   
 
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/depmap.feature

  dgidb:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }   
 
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/dgidb.feature

  drugbank:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/drugbank.feature

  drugcentral:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/drugcentral.feature

  gelinea:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/gelinea.feature

  gtopdb:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }   
 
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/gtopdb.feature

  gwas:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }

        - name: download all the required python modules
          run: pip install -r test/requirements.txt

        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/gwas.feature

  hgnc: 
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
        
        - name: download all the required python modules
          run: pip install -r test/requirements.txt

        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/hgnc.feature

  hmdb:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/hmdb.feature

  kinomescan:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/kinomescan.feature

  molecular-data-provider:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/molecular-data-provider.feature

  molepro-filters:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev } 
   
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/molepro-filters.feature

  moleprodb:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/moleprodb.feature

  node-normalizer:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }

        - name: download all the required python modules
          run: pip install -r test/requirements.txt

        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/node-normalizer.feature 

  probeminer:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
  
        - name: download all the required python modules
          run: pip install -r test/requirements.txt

        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/probeminer.feature

  pharmgkb:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }    
        
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/pharmgkb.feature

  pharos:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }    
        
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/pharos.feature

  pubchem:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev } 

        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/pubchem.feature

  repurposing:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev } 

        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/repurposing.feature

  rxnorm:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }

        - name: download all the required python modules
          run: pip install -r test/requirements.txt

        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/rxnorm.feature

  sider:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }

        - name: download all the required python modules
          run: pip install -r test/requirements.txt

        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/sider.feature


  stitch:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev } 

 
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/stitch.feature

  string:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev } 

        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/string.feature

  trapi:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
        
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/trapi.feature

  uniprot:
    runs-on: ubuntu-latest
    steps:
        - name: Git checkout
          uses: actions/checkout@v2
          with: { ref: test-dev }
          
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/uniprot.feature
