
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# This workflow was programmed to:
#   1. be triggered manually (on: workflow_dispatch:), see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
#   2. be triggered by cron scheduling (on: schedule:) to run at midnight UTC
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# https://github.com/broadinstitute/molecular-data-provider/blob/master/.github/workflows/main.yml
name: Daily testing

on:
  workflow_dispatch:
  schedule:
  - cron: '00 00 * * *'   # midnight UTC

jobs:
# This workflow contains a multiple jobs to test each transformer

  chebi:
    runs-on: ubuntu-latest
    steps:    
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/chebi.feature

  chembank:
    runs-on: ubuntu-latest
    steps:    
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/chembank.feature

  chembl:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/chembl.feature

  cmap:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/cmap.feature

  ctrp:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/ctrp.feature


  depmap:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/depmap.feature

  dgidb:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/dgidb.feature

  drugbank:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/drugbank.feature

  drugcentral:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/drugcentral.feature

  gelinea:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/gelinea.feature

  gtopdb:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/gtopdb.feature

  hmdb:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/hmdb.feature

  molecular-data-provider:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/molecular-data-provider.feature

  pharos:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/pharos.feature

  pubchem:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/pubchem.feature

  repurposing:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/repurposing.feature

  stitch:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/stitch.feature

  trapi:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
    
        - name: download all the required python modules
          run: pip install -r test/requirements.txt
          
        - name: Start the BDD testing of the checked out feature file
          run: behave test/features/trapi.feature
